Added error handling for not-so-special case

diff --git a/hrs b/hrs
--- a/hrs
+++ b/hrs
@@ -50,23 +50,28 @@ EOF
 if [ $# -gt 0 ]; then
     case $1 in
         start|s|st|sta|star)
-            if [ -s "${log}" -a "`tail -1 ${log} | wc -c`" -le "12" ]; then
-                echo "Splitting entry..."
+            if [ -s "${log}" -a "`tail -1 ${log} | wc -c`" -le "11" ]; then
+                echo "Splitting ongoing entry..."
                 shift
-                $0 end $@
+                $0 end $@ || exit 3
             fi
             echo -n "`date +%s` " >> ${log}
             echo "Started entry at: `date +'%F %T'`"
             ;;
         end|e|en)
-            {
-                echo -n "`date +%s`"
-                if [ $# -gt 1 ]; then
-                    shift
-                    echo -n " $@"
-                fi
-                echo ""
-            } >> ${log}
+            if [ -s "${log}" -a "`tail -1 ${log} | wc -c`" -le "11" ]; then
+                {
+                    echo -n "`date +%s`"
+                    if [ $# -gt 1 ]; then
+                        shift
+                        echo -n " $@"
+                    fi
+                    echo ""
+                } >> ${log}
+            else
+                echo "ERROR: Did not find entry to end" >&2
+                exit 3
+            fi
             echo "Ended entry at: `date +'%F %T'`"
             ;;
         edit|ed|edi)
@@ -75,7 +80,7 @@ if [ $# -gt 0 ]; then
         raw|r|ra)
             exec cat ${log}
             ;;
-        -h|--help)
+        -h|--help|help)
             usage
             ;;
         *)
